# Permalinks
permalink:        pretty

# Setup
url:              http://cjamadagni.github.io
baseurl:          /


author:
  name:           'Chirag Jamadagni'
  url:            https://linkedin.com/in/cjamadagni


# Custom vars
github:
  repo:           https://github.com/cjamadagni
