# Permalinks
permalink:        pretty

# Setup
title:            Chirag Jamadagni
description:      '                                                                                                                            '
url:              http://cjamadagni.github.io
baseurl:          /


author:
  name:           'Chirag Jamadagni'
  url:            https://twitter.com/rohitvarkey


# Custom vars
github:
  repo:           https://github.com/cjamadagni
